set_property SRC_FILE_INFO {cfile:D:/vivado_messing_around/project_2/project_2.srcs/constrs_1/new/constraint_led_sw.xdc rfile:../../../project_2.srcs/constrs_1/new/constraint_led_sw.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M26 [get_ports {GPIO_LED[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T24 [get_ports {GPIO_LED[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T25 [get_ports {GPIO_LED[2]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R26 [get_ports {GPIO_LED[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R8 [get_ports {GPIO_DIP_SW[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P8 [get_ports {GPIO_DIP_SW[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R7 [get_ports {GPIO_DIP_SW[2]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R6 [get_ports {GPIO_DIP_SW[3]}]
