# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AC701-tutorials/tutorial_3_ethernet/tutorial_3_ethernet.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
# IP: The module: 'design_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AC701-tutorials/tutorial_3_ethernet/tutorial_3_ethernet.gen/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/AC701-tutorials/tutorial_3_ethernet/tutorial_3_ethernet.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
# IP: The module: 'design_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AC701-tutorials/tutorial_3_ethernet/tutorial_3_ethernet.gen/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
