set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[0]}]
set_property LOC M26 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[1]}]
set_property LOC T24 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[2]}]
set_property LOC T25 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_LED[3]}]
set_property LOC R26 [get_ports {GPIO_LED[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[0]}]
set_property LOC R8 [get_ports {GPIO_DIP_SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[1]}]
set_property LOC P8 [get_ports {GPIO_DIP_SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[2]}]
set_property LOC R7 [get_ports {GPIO_DIP_SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_DIP_SW[3]}]
set_property LOC R6 [get_ports {GPIO_DIP_SW[3]}]
